name = "assetmantle-website"
type = "webpack"
zone_id = '4d52f36b396dad8cddd83b3d5e0fbda4'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-27"
account_id = ${{ secrets.CF_ACCOUNT_ID }}

[env.staging]
routes = ["https://staging.assetmantle.one/*"]

[env.release]
routes = ["https://assetmantle.one/*"]
